#!/bin/sh
command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting '.git/hooks/pre-push'.\n"; exit 2; }
git lfs pre-push "$@"

echo pre-push checks
yarn lint && yarn format
if [ $? -eq 0 ]; 
then
	echo "solhint check is correct"
else
	exit 1
fi
